version: "3.7"
services:


  #############################################################################################
  ###                           Efiling api backend app                                     ###
  #############################################################################################
  mail-it:
    build:
      context: ./src
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin
    networks:
        - mail-it-net

  #############################################################################################
  ###                                 MAIL HOG                                              ###
  #############################################################################################
  mailhog:
    image: "mailhog/mailhog"
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
        - mail-it-net

  #############################################################################################
  ###                                 REDIS SERVER                                          ###
  #############################################################################################
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --requirepass admin
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/data
    restart: always
    networks:
      - mail-it-net

  #############################################################################################
  ###                                 REDIS COMMANDER                                       ###
  #############################################################################################
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - JMT_SPRING_REDIS_PORT=6379
      - JMT_SPRING_REDIS_HOST=redis
      - JMT_SPRING_REDIS_PASSWORD=admin
    ports:
      - "8082:8081"
    networks:
      - mail-it-net

volumes:
  data-redis:
    driver: local

networks:
  mail-it-net:
    driver: "bridge"
