name: Promote Jag Mail IT Image to Prod

on:
  workflow_dispatch:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: latest

      - name: Cluster Login
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL_JRCC }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT4_SA_PASSWORD_JRCC }}"}'
          cmd: |
            'version'
            
      - name: Login to Openshift Docker
        run : |
          docker login ${{ secrets.OPENSHIFT4_EXTERNAL_REPOSITORY_JRCC }} -u ${{ secrets.OPENSHIFT4_SA_USERNAME_JRCC }} -p ${{ secrets.OPENSHIFT4_SA_PASSWORD_JRCC }}

      - name: Build the Docker image
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |          
          docker pull  ${{ secrets.OPENSHIFT4_EXTERNAL_REPOSITORY_JRCC }}/${{ secrets.OPENSHIFT4_TOOLS_NAMESPACE_JRCC }}/mail-it:test
          docker tag ${{ secrets.OPENSHIFT4_EXTERNAL_REPOSITORY_JRCC }}/${{ secrets.OPENSHIFT4_TOOLS_NAMESPACE_JRCC }}/mail-it:test ${{ secrets.OPENSHIFT4_EXTERNAL_REPOSITORY_JRCC }}/${{ secrets.OPENSHIFT4_TOOLS_NAMESPACE_JRCC }}/mail-it:prod
          docker push ${{ secrets.OPENSHIFT4_EXTERNAL_REPOSITORY_JRCC }}/${{ secrets.OPENSHIFT4_TOOLS_NAMESPACE_JRCC }}/mail-it:prod
